function regressors = slice_regressors(o, mean_slice, sd_slice)
% Return regressors for this slice
[fx fy] = gradient(mean_slice);
[fsx fsy] = gradient(sd_slice);
sd2 = sd_slice.^2;
[fsx2 fsy2] = gradient(sd2);
regressors = {...
    mean_slice, ...
    mean_slice .^2, ...
    fx, ...
    fy, ...
    sd_slice, ...
    sd2, ...
    fsx, ...
    fsy, ...
    fsx2,...
    fsy2};
return
